### ISSUE TITLE
Need CODE For Third Eye project 

### ISSUE THREAD

**Issue by suhasreddy007** [imakashsahu/Third-Eye-Final-Year-Project#2]
Bro I am suhas from Bangalore 
I am final year Gard student of Dayanada Sagar University 
so bro I saw one of your videos in YouTube so I got interested in your project,  now my guide is asking for the code so bro can you please give access to code bro
Please 🙏🏼🙏🏼🙏🏼🙏🏼🙏🏼 bro now I don't have anything other than this......

**Comment by maniiiisha** [comment]
Go through the Readme, the source code can be downloaded from the given link.

**Comment by suhasreddy007** [comment]
Where is the message box to pull up the request

**Comment by suhasreddy007** [comment]
Pls help me here

**Comment by maniiiisha** [comment]
In the README.md file of this project there is a section of source code, under which "Download Source Code" is written.

**Comment by suhasreddy007** [comment]
Yep I know but it is showing for me like this!
[Screenshot_20220406-235832_GitHub.jpg](https://user-images.githubusercontent.com/94061162/162043722-63c7430c-1fe1-43e6-b62a-0faddfa98c23.jpg)

After I clicked on that link then it's buffering, and showing like it's empty like this
![Screenshot_20220406-235841_Drive.jpg](https://user-images.githubusercontent.com/94061162/162044020-89f6b611-0945-407b-b9f8-badc45907df2.jpg)

Pls can u suggest me how to do this
My whatsapp no:  9535077156
🙏🏼🙏🏼🙏🏼🙏🏼

**Comment by maniiiisha** [comment]
Try it from laptop or pc.

**Comment by REAPERAWP** [comment]
@suhasreddy007 contact me by Email at beprojectf@gmail.com to help you run this project

**Comment by bhumikabokde11** [comment]
hey guys can you please help me with this project source code. i have tried multiple times to download this source code file but after downloading last min it gets failed maybe that drive file is restricted for the unknown users, please give me the access pf source code or help me with downloading the sorce code
